requires "Mojo::UserAgent";
requires "IO::Socket::SSL", "> 2.009";
requires "File::Slurper";
requires "Git";
requires "JSON";
requires "YAML";
requires "Term::ANSIColor";
requires "Net::Ping";
requires "GitHub::Actions";
requires "LWP::UserAgent";
requires "App::FatPacker";
